services:
  perplexica-backend:
    image: taamsoft/search:v1
    ports:
      - 3009:3001
    volumes:
      - ./data:/home/perplexica/data
      - ./uploads:/home/perplexica/uploads
      - ./config.toml:/home/perplexica/config.toml
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - perplexica-network
    restart: unless-stopped

  perplexica-frontend:
    image: taamsoft/s_frontend:v1
    depends_on:
      - perplexica-backend
    ports:
      - 3008:3000
    networks:
      - perplexica-network
    restart: unless-stopped

networks:
  perplexica-network:
